name: windowsCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 6.0.x
    AZURE_WEBAPP_NAME: locmaui    # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    
jobs:
  buildWindows:
   # if: "contains(github.event.commits[0].message, '[win]')"
    runs-on: windows-2022
    
    steps:
     - uses: actions/checkout@v2
      
     - name: Setup .NET SDK ${{env.DOTNETVERSION}}
       uses: actions/setup-dotnet@v1
       with:
              dotnet-version: '${{env.DOTNETVERSION}}'


     # https://docs.microsoft.com/en-us/windows/msix/desktop/azure-dev-ops
     - name: Sign Windows App
       shell: pwsh
       run: |
        try {
             cd "C:\Program Files (x86)\Windows Kits\10\App Certification Kit\"
             ls
            # .\signtool.exe sign /a /v /fd SHA256 /f  "$secretFile | select fullname" /p ($env:CERT_PASSWORD) LoanOffersCalculatorMAUI\bin\Release\net6.0-windows10.0.19041.0\win10-x64\AppPackages\LoanOffersCalculatorMAUI_1.0.0.1_TestLoanOffersCalculatorMAUI_1.0.0.1_x64.msix
             }
         catch {
          Write-Error "An error occurred: $_"
          exit 1
         }

       
           # Set the full path to signtool.exe
          # $signtoolPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe"
           


      
